# Generated by Django 5.0.8 on 2025-09-19 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('properties', '0004_alter_propertytype_options_property_cadastral_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id_number', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('number_of_dependents', models.PositiveIntegerField(default=0)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('business_owner', 'Business Owner')], max_length=20)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('employer_address', models.TextField(blank=True)),
                ('employer_phone', models.CharField(blank=True, max_length=17)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('monthly_income_range', models.CharField(blank=True, choices=[('0-100k', '0 - 100,000 XAF'), ('100k-250k', '100,000 - 250,000 XAF'), ('250k-500k', '250,000 - 500,000 XAF'), ('500k-1m', '500,000 - 1,000,000 XAF'), ('1m-2m', '1,000,000 - 2,000,000 XAF'), ('2m+', '2,000,000+ XAF')], max_length=20)),
                ('employment_duration', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17)),
                ('emergency_contact_address', models.TextField(blank=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=100)),
                ('guarantor_phone', models.CharField(blank=True, max_length=17)),
                ('guarantor_email', models.EmailField(blank=True, max_length=254)),
                ('guarantor_address', models.TextField(blank=True)),
                ('guarantor_id_document', models.FileField(blank=True, null=True, upload_to='tenant_documents/guarantor/')),
                ('id_document_front', models.FileField(blank=True, null=True, upload_to='tenant_documents/id/')),
                ('id_document_back', models.FileField(blank=True, null=True, upload_to='tenant_documents/id/')),
                ('employment_certificate', models.FileField(blank=True, null=True, upload_to='tenant_documents/employment/')),
                ('income_statement', models.FileField(blank=True, null=True, upload_to='tenant_documents/income/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='tenant_documents/bank/')),
                ('preferred_property_type', models.CharField(blank=True, max_length=50)),
                ('max_rent_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_bedrooms', models.PositiveIntegerField(default=1)),
                ('requires_furnished', models.BooleanField(default=False)),
                ('has_pets', models.BooleanField(default=False)),
                ('pet_description', models.TextField(blank=True)),
                ('current_address', models.TextField(blank=True)),
                ('previous_landlord_name', models.CharField(blank=True, max_length=100)),
                ('previous_landlord_phone', models.CharField(blank=True, max_length=17)),
                ('reason_for_moving', models.TextField(blank=True)),
                ('rental_history_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(850)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_areas', models.ManyToManyField(blank=True, to='locations.area')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='tenant_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenants.tenantprofile',),
        ),
        migrations.CreateModel(
            name='TenantReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('employer', 'Employer'), ('previous_landlord', 'Previous Landlord'), ('personal', 'Personal Reference'), ('professional', 'Professional Reference')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_duration', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('reference_feedback', models.TextField(blank=True)),
                ('recommendation_level', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='tenants.tenantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('desired_move_in_date', models.DateField()),
                ('lease_duration_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('offered_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_occupants', models.TextField(blank=True, help_text='List additional people who will live in the property')),
                ('special_requests', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True, help_text="Why you're interested in this property")),
                ('review_notes', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_applications', to='properties.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tenants.tenantprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'property')},
            },
        ),
    ]
