# Generated by Django 5.0.8 on 2025-09-19 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenantprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='government_id_upload',
            field=models.FileField(blank=True, null=True, upload_to='tenant_documents/government_id/'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='land_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='lease_agreement_acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='preferred_amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of preferred amenities'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='property_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='property_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
