# Generated by Django 5.0.8 on 2025-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantprofile_budget_max_tenantprofile_budget_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='taxpayer_card',
            field=models.FileField(blank=True, null=True, upload_to='tenant_documents/taxpayer/'),
        ),
    ]
