# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_properties__is_acti_3d1e25_idx_and_more'),
        ('tenants', '0004_tenantprofile_taxpayer_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenantapplication',
            index=models.Index(fields=['property', 'status'], name='tenants_ten_propert_8e8d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantapplication',
            index=models.Index(fields=['status', 'submitted_at'], name='tenants_ten_status_e7c7ef_idx'),
        ),
    ]
