# Generated by Django 5.0.8 on 2025-09-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='address_verification',
            field=models.FileField(blank=True, null=True, upload_to='agent_documents/address/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='country',
            field=models.CharField(default='CM', max_length=2),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='data_consent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_documents/id/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID')], default='national_id', max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_mobile_money_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='mobile_money_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='mobile_money_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='mobile_money_provider',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('other', 'Other')], default='mtn', max_length=10),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='name_match_status',
            field=models.CharField(choices=[('match', 'Match'), ('close', 'Close Match'), ('mismatch', 'Mismatch'), ('pending', 'Pending Verification')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='residence_proof',
            field=models.FileField(blank=True, null=True, upload_to='agent_documents/residence/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='selfie_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_documents/selfie/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='taxpayer_card',
            field=models.FileField(blank=True, null=True, upload_to='agent_documents/taxpayer/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
