# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentprofile_address_verification_agentprofile_city_and_more'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['is_active', 'is_verified', 'is_featured'], name='agents_agen_is_acti_a4435e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentprofile',
            index=models.Index(fields=['is_active', 'specialization'], name='agents_agen_is_acti_b4adc0_idx'),
        ),
    ]
