# Generated by Django 5.1.2 on 2025-10-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Username, email, or phone number', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', '-created_at'], name='authenticat_identif_51df79_idx'), models.Index(fields=['ip_address', '-created_at'], name='authenticat_ip_addr_fe7bd0_idx'), models.Index(fields=['user', '-created_at'], name='authenticat_user_id_86123e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('phone', 'Phone Verification'), ('email', 'Email Verification')], max_length=10)),
                ('purpose', models.CharField(choices=[('signup', 'Signup Verification'), ('login', 'Login Verification'), ('password_reset', 'Password Reset'), ('phone_change', 'Phone Number Change')], max_length=20)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('recipient', models.CharField(help_text='Phone number or email address', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, help_text='User (null for signup OTP)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'otp_type', 'is_verified'], name='authenticat_recipie_b1f827_idx'), models.Index(fields=['otp_code', 'expires_at'], name='authenticat_otp_cod_208322_idx'), models.Index(fields=['user', '-created_at'], name='authenticat_user_id_5cdbe3_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_used'], name='authenticat_token_176060_idx'), models.Index(fields=['user', '-created_at'], name='authenticat_user_id_96e50f_idx')],
            },
        ),
    ]
