# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['provider_type', 'is_active', 'is_verified'], name='maintenance_provide_9736d8_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_emergency_available'], name='maintenance_is_emer_336a02_idx'),
        ),
    ]
