# Generated by Django 5.0.8 on 2025-09-17 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_agent_commission_months_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='property',
            name='cadastral_id',
            field=models.CharField(blank=True, help_text='Official registry/cadastral ID', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='registry_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Verification'), ('verified', 'Registry Verified'), ('disputed', 'Disputed'), ('invalid', 'Invalid/Not Found')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='title_document',
            field=models.FileField(blank=True, help_text='Upload land title certificate', null=True, upload_to='property_titles/'),
        ),
        migrations.AddField(
            model_name='property',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertystatus',
            name='allows_inquiries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='subtype',
            field=models.CharField(blank=True, choices=[('chambre_modern', 'Chambre Modern/Room'), ('studio', 'Studio'), ('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('villa_duplex', 'Villa/Duplex'), ('guest_house', 'Guest House'), ('land_plot', 'Land Plot'), ('office', 'Office'), ('shop', 'Shop/Store'), ('warehouse', 'Warehouse'), ('commercial_land', 'Commercial Land'), ('industrial', 'Industrial Space')], max_length=20),
        ),
        migrations.AlterField(
            model_name='propertystatus',
            name='name',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('available', 'Available'), ('under_offer', 'Under Offer'), ('pending', 'Pending'), ('sold', 'Sold'), ('rented', 'Rented'), ('withdrawn', 'Withdrawn')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_id', models.CharField(max_length=50, unique=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ownership_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('land_title', 'Land Title Certificate'), ('survey_plan', 'Survey Plan'), ('building_permit', 'Building Permit'), ('occupancy_certificate', 'Certificate of Occupancy'), ('tax_receipt', 'Property Tax Receipt'), ('ownership_proof', 'Proof of Ownership')], max_length=25)),
                ('document_file', models.FileField(upload_to='property_documents/')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Document Expired')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='properties.property')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_document_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'document_type')},
            },
        ),
    ]
