# Generated by Django 5.1.2 on 2025-10-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='google_pin_location',
        ),
    ]
