# Generated by Django 5.1.2 on 2025-10-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_google_pin_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='verified',
        ),
        migrations.AlterField(
            model_name='property',
            name='cadastral_id',
            field=models.CharField(blank=True, help_text='Official cadastral registry ID', max_length=100),
        ),
    ]
