# Generated by Django 5.1.2 on 2025-10-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, help_text='Unique code (e.g., RESIDENTIAL, apartment)', max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='properties.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('underoffer', 'Under Offer'), ('pending', 'Pending'), ('inactive', 'Inactive'), ('new', 'New'), ('construction', 'Under Construction'), ('offplan', 'Off Plan'), ('reserved', 'Reserved'), ('expired', 'Expired'), ('draft', 'Draft')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#10B981', help_text='Status badge color', max_length=7)),
                ('allows_inquiries', models.BooleanField(default=True, help_text='Can users inquire about properties in this state?')),
                ('is_publicly_visible', models.BooleanField(default=True, help_text='Show properties in this state on public listings')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applies_to', models.ManyToManyField(blank=True, help_text='Categories this state applies to (empty = applies to all)', related_name='states', to='properties.category')),
            ],
            options={
                'verbose_name': 'Property State',
                'verbose_name_plural': 'Property States',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI display', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applies_to', models.ManyToManyField(blank=True, help_text='Categories this tag applies to (empty = applies to all)', related_name='tags', to='properties.category')),
            ],
            options={
                'verbose_name': 'Property Tag',
                'verbose_name_plural': 'Property Tags',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='properties__slug_96ba58_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='properties__parent__a6da5f_idx'),
        ),
    ]
