# Generated by Django 5.1.2 on 2025-10-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_category_propertystate_propertytag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent_commission_percentage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='room_size',
        ),
    ]
