# Generated by Django 5.1.2 on 2026-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_room_size_and_commission_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Property latitude (falls back to area latitude if not set)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Property longitude (falls back to area longitude if not set)', max_digits=9, null=True),
        ),
    ]
