# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentprofile_agents_agen_is_acti_a4435e_idx_and_more'),
        ('locations', '0001_initial'),
        ('properties', '0011_add_property_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'created_at'], name='properties__is_acti_3d1e25_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agent', 'is_active'], name='properties__agent_i_184dad_idx'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['category', 'is_active'], name='properties__categor_306b2a_idx'),
        ),
    ]
