# Generated by Django 5.2.12 on 2026-04-17 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_properties__is_acti_3d1e25_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySearchSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_slug', models.CharField(db_index=True, max_length=250)),
                ('action', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_sync_events', to='properties.property')),
            ],
            options={
                'ordering': ['available_at', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertysearchsync',
            index=models.Index(fields=['status', 'available_at'], name='properties__status_c1a2d5_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysearchsync',
            index=models.Index(fields=['property_slug', 'status'], name='properties__propert_5bce89_idx'),
        ),
        migrations.AddIndex(
            model_name='propertysearchsync',
            index=models.Index(fields=['action', 'status'], name='properties__action_8cc34f_idx'),
        ),
    ]