# Generated by Django 5.0.8 on 2025-09-17 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('properties', '0004_alter_propertytype_options_property_cadastral_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('this_month_views', models.PositiveIntegerField(default=0)),
                ('total_inquiries', models.PositiveIntegerField(default=0)),
                ('this_month_inquiries', models.PositiveIntegerField(default=0)),
                ('days_on_market', models.PositiveIntegerField(default=0)),
                ('average_time_to_respond', models.DecimalField(decimal_places=2, default=0, help_text='Average response time in hours', max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_analytics', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Property Analytics',
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties_listed', models.PositiveIntegerField(default=0)),
                ('properties_rented', models.PositiveIntegerField(default=0)),
                ('properties_sold', models.PositiveIntegerField(default=0)),
                ('inquiries_sent', models.PositiveIntegerField(default=0)),
                ('inquiries_received', models.PositiveIntegerField(default=0)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0, help_text='Response rate as percentage', max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Analytics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('property_views', 'Property Views'), ('property_inquiries', 'Property Inquiries'), ('user_registrations', 'User Registrations'), ('lease_signings', 'Lease Signings'), ('rent_collections', 'Rent Collections'), ('maintenance_requests', 'Maintenance Requests'), ('occupancy_rate', 'Occupancy Rate'), ('revenue', 'Revenue')], max_length=30)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='locations.area')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('metric_type', 'date', 'property', 'user', 'area')},
            },
        ),
        migrations.CreateModel(
            name='MarketAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('occupancy_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Occupancy rate as percentage', max_digits=5, null=True)),
                ('new_listings', models.PositiveIntegerField(default=0)),
                ('closed_deals', models.PositiveIntegerField(default=0)),
                ('average_days_on_market', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_analytics', to='locations.area')),
            ],
            options={
                'ordering': ['-date', 'area'],
                'unique_together': {('area', 'date')},
            },
        ),
    ]
