# Generated by Django 4.2.24 on 2025-10-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotedproperty',
            options={'ordering': ['-priority_score', '-created_at'], 'verbose_name_plural': 'Promoted Properties'},
        ),
    ]
