# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_alter_promotedproperty_options'),
        ('agents', '0002_agentprofile_address_verification_agentprofile_city_and_more'),
        ('properties', '0011_add_property_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='ad_advertis_status_dbceec_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['advertiser', 'status'], name='ad_advertis_adverti_7afdbb_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['placement'], name='ad_advertis_placeme_0dfbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='promotedproperty',
            index=models.Index(fields=['is_active', 'promotion_type', 'start_date', 'end_date'], name='ad_promoted_is_acti_d98760_idx'),
        ),
        migrations.AddIndex(
            model_name='promotedproperty',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='ad_promoted_is_acti_86baa8_idx'),
        ),
    ]
