# Generated by Django 5.0.8 on 2025-09-17 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('properties', '0004_alter_propertytype_options_property_cadastral_id_and_more'),
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_content', models.TextField(help_text='Lease template with placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('initial_months_payable', models.PositiveIntegerField(default=1, help_text='Number of months rent paid upfront', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit (caution)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('caution_months', models.PositiveIntegerField(default=0, help_text='Caution expressed in months of rent', validators=[django.core.validators.MaxValueValidator(12)])),
                ('agency_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('contract_registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('terms', models.TextField(blank=True, help_text='Lease terms and conditions')),
                ('lease_document', models.FileField(blank=True, null=True, upload_to='leases/documents/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('tenant_signed', models.BooleanField(default=False)),
                ('tenant_signature_date', models.DateTimeField(blank=True, null=True)),
                ('landlord_signed', models.BooleanField(default=False)),
                ('landlord_signature_date', models.DateTimeField(blank=True, null=True)),
                ('agent_signed', models.BooleanField(default=False)),
                ('agent_signature_date', models.DateTimeField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('termination_notice_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, choices=[('expired', 'Natural Expiration'), ('tenant_request', 'Tenant Request'), ('landlord_request', 'Landlord Request'), ('breach', 'Contract Breach'), ('non_payment', 'Non-Payment'), ('property_sale', 'Property Sale'), ('renovation', 'Property Renovation')], max_length=20)),
                ('termination_details', models.TextField(blank=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('renewal_notice_days', models.PositiveIntegerField(default=30, help_text='Days notice required before renewal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentprofile')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_leases', to=settings.AUTH_USER_MODEL)),
                ('rental_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_agreements', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenants.tenantprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leases.leasetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('late_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('late_fee_waived', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedule', to='leases.leaseagreement')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['status', 'start_date'], name='leases_leas_status_daccc1_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__4d663b_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['rental_property', 'status'], name='leases_leas_rental__ed4587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentschedule',
            unique_together={('lease', 'due_date')},
        ),
    ]
