# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentprofile_agents_agen_is_acti_a4435e_idx_and_more'),
        ('leases', '0001_initial'),
        ('properties', '0011_add_property_coordinates'),
        ('tenants', '0004_tenantprofile_taxpayer_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['landlord', 'status'], name='leases_leas_landlor_8f51d3_idx'),
        ),
        migrations.AddIndex(
            model_name='leaseagreement',
            index=models.Index(fields=['status', 'end_date'], name='leases_leas_status_6dca49_idx'),
        ),
        migrations.AddIndex(
            model_name='rentschedule',
            index=models.Index(fields=['is_paid', 'due_date'], name='leases_rent_is_paid_e365d9_idx'),
        ),
    ]
