# Generated by Django 4.2.24 on 2025-10-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediafile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatag',
            options={'ordering': ['name'], 'verbose_name_plural': 'Media Tags'},
        ),
    ]
