# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_mediatag_options'),
        ('properties', '0011_add_property_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['property', 'file_type', 'is_active'], name='media_media_propert_30382a_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='media_prope_propert_8d663d_idx'),
        ),
    ]
