# Generated by Django 5.0.8 on 2025-09-17 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_initial'),
        ('leases', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('payment', '0002_initial'),
        ('properties', '0004_alter_propertytype_options_property_cadastral_id_and_more'),
        ('tariffplans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_buyer', 'Resolved - Buyer Favor'), ('resolved_seller', 'Resolved - Seller Favor'), ('resolved_split', 'Resolved - Split'), ('closed', 'Closed')], default='open', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Escrow Created'), ('payment_initiated', 'Payment Initiated'), ('proof_uploaded', 'Payment Proof Uploaded'), ('payment_confirmed', 'Payment Confirmed'), ('funds_held', 'Funds Held'), ('released', 'Funds Released'), ('refunded', 'Funds Refunded'), ('disputed', 'Dispute Opened'), ('expired', 'Escrow Expired'), ('admin_action', 'Admin Action')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('express_union', 'Express Union Mobile')], max_length=20)),
                ('phone_number', models.CharField(max_length=17)),
                ('account_name', models.CharField(help_text='Name on mobile money account', max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('name_mismatch', 'Name Mismatch')], default='pending', max_length=15)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('name_match_score', models.DecimalField(blank=True, decimal_places=2, help_text='Fuzzy match score with ID name', max_digits=5, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_file', models.FileField(upload_to='payment_proofs/')),
                ('description', models.TextField(blank=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='routing_number',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='swift_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_usd',
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='phone_number',
            field=models.CharField(blank=True, help_text='For mobile money accounts', max_length=17),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_type',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('stripe', 'Stripe (Cards)'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('flutterwave', 'Flutterwave'), ('korapay', 'KoraPay')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='supports_escrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='leases.leaseagreement'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='maintenance.maintenancerequest'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='momo_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for mobile money transactions', max_length=17),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate to XAF', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment.currency'),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_type',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('momo_account', 'Mobile Money'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('wallet', 'Digital Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=2000000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payment.currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('rent_payment', 'Rent Payment'), ('deposit_payment', 'Security Deposit'), ('commission_payment', 'Agent Commission'), ('maintenance_payment', 'Maintenance Payment'), ('escrow_funding', 'Escrow Funding'), ('escrow_release', 'Escrow Release'), ('ad_payment', 'Advertisement Payment'), ('subscription', 'Subscription Payment'), ('refund', 'Refund'), ('penalty', 'Penalty Fee'), ('bonus', 'Bonus Credit')], max_length=20),
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.CharField(max_length=20, unique=True)),
                ('escrow_type', models.CharField(choices=[('deposit', 'Security Deposit'), ('sale', 'Property Sale'), ('rent_advance', 'Rent Advance Payment'), ('commission', 'Agent Commission')], max_length=15)),
                ('status', models.CharField(choices=[('created', 'Created'), ('awaiting_payment', 'Awaiting Payment'), ('paid_pending_confirm', 'Paid - Pending Confirmation'), ('held', 'Funds Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terms', models.TextField(help_text='Escrow terms and conditions')),
                ('release_conditions', models.TextField(help_text='Conditions for fund release')),
                ('expires_at', models.DateTimeField(help_text='Payment deadline')),
                ('release_deadline', models.DateTimeField(blank=True, help_text='Auto-release deadline if no action taken', null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_proof_uploaded', models.BooleanField(default=False)),
                ('payment_confirmed_by_seller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_escrows', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.currency')),
                ('forced_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_actions', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.paymentmethod')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='properties.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_escrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='escrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.escrow'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['phone_number'], name='payment_tra_phone_n_f1a3e6_idx'),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='escrow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='payment.escrow'),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowevent',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payment.escrow'),
        ),
        migrations.AddField(
            model_name='mobilemoneyaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilemoneyaccount',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_momo_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='escrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='payment.escrow'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_proofs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mobilemoneyaccount',
            unique_together={('user', 'provider', 'phone_number')},
        ),
    ]
