# Generated by Django 5.1.2 on 2026-04-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_escrowdispute_escrowevent_mobilemoneyaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_type',
            field=models.CharField(choices=[('momo_account', 'Mobile Money'), ('flutterwave', 'Flutterwave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gateway_type',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('flutterwave', 'Flutterwave')], default='mtn_momo', max_length=20),
        ),
    ]
