# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_advertisement_ad_advertis_status_dbceec_idx_and_more'),
        ('leases', '0002_leaseagreement_leases_leas_landlor_8f51d3_idx_and_more'),
        ('maintenance', '0002_serviceprovider_maintenance_provide_9736d8_idx_and_more'),
        ('payment', '0004_remove_unused_payment_gateways'),
        ('properties', '0011_add_property_coordinates'),
        ('tariffplans', '0003_usersubscription_tariffplans_user_id_15a306_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status', 'expires_at'], name='payment_esc_status_4f2d45_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['buyer', 'status'], name='payment_esc_buyer_i_ece4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['seller', 'status'], name='payment_esc_seller__75daca_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='payment_inv_user_id_8af95b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='payment_inv_status_a08799_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payment_tra_status_373de7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='payment_tra_created_0d0f1d_idx'),
        ),
    ]
