# Generated by Django 5.0.8 on 2025-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertytype_options_property_cadastral_id_and_more'),
        ('users', '0002_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_property_types',
            field=models.ManyToManyField(blank=True, help_text='Preferred property types for alerts', to='properties.propertytype'),
        ),
    ]
