# Generated by Django 5.0.8 on 2025-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_preferred_property_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('agent', 'Real Estate Agent'), ('admin', 'Admin')], default='tenant', max_length=10),
        ),
    ]
