# Generated by Django 5.0.8 on 2025-09-19 11:51

from django.db import migrations


def update_user_types(apps, schema_editor):
    """Update existing user types from old to new system"""
    CustomUser = apps.get_model('users', 'CustomUser')

    # Update client users to tenant
    CustomUser.objects.filter(user_type='client').update(user_type='tenant')
    # Update landlord users to tenant (as they can now be tenants too)
    CustomUser.objects.filter(user_type='landlord').update(user_type='tenant')


def reverse_user_types(apps, schema_editor):
    """Reverse migration: change tenant back to client"""
    CustomUser = apps.get_model('users', 'CustomUser')

    # This is a simplification, we can't perfectly reverse
    CustomUser.objects.filter(user_type='tenant').update(user_type='client')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RunPython(update_user_types, reverse_user_types),
    ]
