# Generated by Django 5.1.2 on 2026-04-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0001_initial'),
        ('users', '0007_alter_userpreferences_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'is_suspended'], name='users_custo_user_ty_bfe469_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'is_phone_verified'], name='users_custo_user_ty_02a034_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='users_custo_user_ty_f25e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['user', 'verification_type', 'status'], name='users_userv_user_id_bad372_idx'),
        ),
        migrations.AddIndex(
            model_name='userverification',
            index=models.Index(fields=['status', 'expires_at'], name='users_userv_status_f13df8_idx'),
        ),
    ]
