name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks
        env:
          USE_SQLITE: 'true'
        working-directory: backend
        run: |
          python manage.py check

      - name: Run migrations
        env:
          USE_SQLITE: 'true'
        working-directory: backend
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        env:
          USE_SQLITE: 'true'
        working-directory: backend
        run: |
          python manage.py test --verbosity=1
